### ISSUE TITLE
ImportError: No module named _formulas.screen OR _formulas.net.Stream

### ISSUE THREAD

**Issue by cyberbiosecurity** [pyformulas/pyformulas#1]
1) Installation via pip resulted in almost empty dir within Python27\lib\site-packages\pyformulas\
2) So i manually placed files from this repo into
lib\site-packages\pyformulas\, 
which gave another error:
ImportError: No module named _formulas.net.Stream
3) So i figured out maybe we need empty  __ init __.py files in
    "C:\Python27\Lib\site-packages\pyformulas\_formulas\"
    "C:\Python27\Lib\site-packages\pyformulas\_formulas\net\"
So i created them and yes it works. Thank you for this package !

(This is my first bugreport and bugfix  lol welcome me software debugging mofo. gotta go read how this done right.)

**Comment by pyformulas** [comment]
Thank you for the bug report, @cocolacre. Glad you find it useful. This package was developed for Python 3, and I'm not supporting Python 2 at the moment. Perhaps you can check if it installs correctly on a Python 3 installation. Also, the correct way to use the package is as follows:

```
import pyformulas as pf
pf.screen()
class telnet(pf.net.Stream):
    pass
# etc
```
as opposed to:
```
import pyformulas as pf
pf._formulas.screen()
```
